[tool.poetry]
name = "Villager-Bot"
version = "2.0.0"
description = "Economy, utility, fun, Minecraft, and MORE! You name it? We got it! We have multi-language support too! Español! Français!"
authors = ["Milo Weinberg <iapetus011@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7.3"
"discord.py" = "^1.7.1"
aiohttp = "^3.7.4"
aio-mc-rcon = "^3.0.2"
arrow = "^1.1.0"
async-cse = "^0.3.0"
asyncpg = "^0.22.0"
bs4 = "^0.0.1"
cryptography = "^3.4.6"
numpy = "^1.20.1"
opencv-python = "^4.5.1"
psutil = "^5.8.0"
aiofiles = "^0.6.0"
Cython = "^0.29.23"

[tool.poetry.dev-dependencies]
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
